# common:
#     lid_topic:  "/royale_cam0/point_cloud_0"
#     imu_topic:  "/livox/imu"
#     time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
#     time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
#                                   # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

# preprocess:
#     lidar_type: 4                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
#     scan_line: 4
#     blind: 0.3

# mapping:
#     acc_cov: 0.1
#     gyr_cov: 0.1
#     b_acc_cov: 0.0001
#     b_gyr_cov: 0.0001
#     fov_degree:    56
#     det_range:     4
#     extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic
#     extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
#     extrinsic_R: [ 0, 0, 1,
#                    -1, 0, 0,
#                    0, -1, 0]

# publish:
#     path_en:  true
#     scan_publish_en:  true       # false: close all the point cloud output
#     dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
#     scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

# pcd_save:
#     pcd_save_en: true
#     interval: -1                 # how many LiDAR frames saved in each pcd file; 
#                                  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
common:
    #lid_topic:  "/processed_points"
    #lid_topic:  "/filtered_points"
    lid_topic:  "/royale_cam0/point_cloud_0"
    
    # imu_topic:  "/livox/imu"
    imu_topic:  "/handsfree/imu"
    time_sync_en: true         
    time_offset_lidar_to_imu: 0  # 更新的时间偏移

preprocess:
    lidar_type: 4                
    scan_line: 172 #高有172，视为172条线。height。每个点的ring表为所在height
    blind: 0.1
    Frequency: 30 #TOF HZ,5/15/30/60
mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    56
    det_range:     4
    extrinsic_est_en:  true      
    extrinsic_T: [0.02, 0.0, 0.05] # 更新的平移向量
    extrinsic_R: [ 0, 0, 1.00,
                 -1.00, 0.00, 0,
                0.00, -1.00, 0 ] # 更新的旋转矩阵,The extrinsic parameters in FAST-LIO is defined as the LiDAR's pose (position and rotation matrix) in IMU body frame (i.e. the IMU is the base frame). They can be found in the official manual.
    # extrinsic_R: [ 1, 0, 0,
    #                0, 1.00, 0,
    #                0, 0, 1 ] # 更新的旋转矩阵


publish:
    path_en:  true
    scan_publish_en:  true       
    dense_publish_en: true       
    scan_bodyframe_pub_en: true  

pcd_save:
    pcd_save_en: true
    interval: -1                  